import vgamepad as vg

button_map = {
    "X": vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
    "O": vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
    "D": vg.XUSB_BUTTON.XUSB_GAMEPAD_X,   # Square
    "A": vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,   # Triangle

    "UP": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
    "DN": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
    "LF": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
    "RG": vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,

    "L1": vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
    "R1": vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,

    "ST": vg.XUSB_BUTTON.XUSB_GAMEPAD_START,
    "SL": vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK,
}